export const API_BASE = process.env.NEXT_PUBLIC_BASE_API;

//system

export const LOAD_QUOTES = 'LOAD_QUOTES';
export type LOAD_QUOTES = typeof LOAD_QUOTES;

export const LOAD_GENDERS = 'LOAD_GENDERS';
export type LOAD_GENDERS = typeof LOAD_GENDERS;

export const LOAD_MEMBER_STATUS = 'LOAD_MEMBER_STATUS';
export type LOAD_MEMBER_STATUS = typeof LOAD_MEMBER_STATUS;

export const LOAD_EXERCISES = 'LOAD_EXERCISES';
export type LOAD_EXERCISES = typeof LOAD_EXERCISES;

export const LOAD_EXERCISE_MUSCLE_GROUPS = 'LOAD_EXERCISE_MUSCLE_GROUPS';
export type LOAD_EXERCISE_MUSCLE_GROUPS = typeof LOAD_EXERCISE_MUSCLE_GROUPS;

export const LOAD_EXERCISE_TYPES = 'LOAD_EXERCISE_TYPES';
export type LOAD_EXERCISE_TYPES = typeof LOAD_EXERCISE_TYPES;

export const LOAD_TEMPLATE_DIFFICULTY = 'LOAD_TEMPLATE_DIFFICULTY';
export type LOAD_TEMPLATE_DIFFICULTY = typeof LOAD_TEMPLATE_DIFFICULTY;

export const LOAD_REPSCHEME_TYPES = 'LOAD_REPSCHEME_TYPES';
export type LOAD_REPSCHEME_TYPES = typeof LOAD_REPSCHEME_TYPES;

export const REGISTER_USER = 'REGISTER_USER';
export type REGISTER_USER = typeof REGISTER_USER;

export const LOGIN_USER = 'LOGIN_USER';
export type LOGIN_USER = typeof LOGIN_USER;

export const CREATE_FIRST_VISIT_STATS = 'CREATE_FIRST_VISIT_STATS';
export type CREATE_FIRST_VISIT_STATS = typeof CREATE_FIRST_VISIT_STATS;

export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';
export type DEAUTHENTICATE_USER = typeof DEAUTHENTICATE_USER;

export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export type LOAD_USER_PROFILE = typeof LOAD_USER_PROFILE;

export const DESTROY_SESSION = 'DESTROY_SESSION';
export type DESTROY_SESSION = typeof DESTROY_SESSION;
