export const API_BASE = process.env.REACT_APP_BASE_API;
//export const API_BASE = 'http://178.62.117.189/api/';

//system

export const LOAD_QUOTES = 'LOAD_QUOTES';
export type LOAD_QUOTES = typeof LOAD_QUOTES;

export const LOAD_GENDERS = 'LOAD_GENDERS';
export type LOAD_GENDERS = typeof LOAD_GENDERS;

export const LOAD_MEMBER_STATUS = 'LOAD_MEMBER_STATUS';
export type LOAD_MEMBER_STATUS = typeof LOAD_MEMBER_STATUS;

export const LOAD_EXERCISES = 'LOAD_EXERCISES';
export type LOAD_EXERCISES = typeof LOAD_EXERCISES;

export const LOAD_UNAPPROVED_EXERCISES = 'LOAD_UNAPPROVED_EXERCISES';
export type LOAD_UNAPPROVED_EXERCISES = typeof LOAD_UNAPPROVED_EXERCISES;

export const UPDATE_EXERCISE_ADMIN = 'UPDATE_EXERCISE_ADMIN';
export type UPDATE_EXERCISE_ADMIN = typeof UPDATE_EXERCISE_ADMIN;

export const LOAD_EXERCISE_MUSCLE_GROUPS = 'LOAD_EXERCISE_MUSCLE_GROUPS';
export type LOAD_EXERCISE_MUSCLE_GROUPS = typeof LOAD_EXERCISE_MUSCLE_GROUPS;

export const LOAD_EXERCISE_TYPES = 'LOAD_EXERCISE_TYPES';
export type LOAD_EXERCISE_TYPES = typeof LOAD_EXERCISE_TYPES;

export const LOAD_TEMPLATE_DIFFICULTY = 'LOAD_TEMPLATE_DIFFICULTY';
export type LOAD_TEMPLATE_DIFFICULTY = typeof LOAD_TEMPLATE_DIFFICULTY;

export const LOAD_REPSCHEME_TYPES = 'LOAD_REPSCHEME_TYPES';
export type LOAD_REPSCHEME_TYPES = typeof LOAD_REPSCHEME_TYPES;

export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR';
export type AUTHENTICATE_USER_ERROR = typeof AUTHENTICATE_USER_ERROR;

export const LOAD_ALL_ADMIN_USERS = 'LOAD_ALL_ADMIN_USERS';
export type LOAD_ALL_ADMIN_USERS = typeof LOAD_ALL_ADMIN_USERS;

//lifting stats
export const CREATE_LIFTING_STAT = 'CREATE_LIFTING_STAT';
export type CREATE_LIFTING_STAT = typeof CREATE_LIFTING_STAT;

export const CREATE_LIFTING_STAT_COLLECTION = 'CREATE_LIFTING_STAT_COLLECTION';
export type CREATE_LIFTING_STAT_COLLECTION = typeof CREATE_LIFTING_STAT_COLLECTION;

export const UPDATE_LIFTING_STAT = 'UPDATE_LIFTING_STAT';
export type UPDATE_LIFTING_STAT = typeof UPDATE_LIFTING_STAT;

export const UPDATE_LIFTING_STAT_COLLECTION = 'UPDATE_LIFTING_STAT_COLLECTION';
export type UPDATE_LIFTING_STAT_COLLECTION = typeof UPDATE_LIFTING_STAT_COLLECTION;

export const DELETE_LIFTING_STAT_OPTIMISTIC = 'DELETE_LIFTING_STAT_OPTIMISTIC';
export type DELETE_LIFTING_STAT_OPTIMISTIC = typeof DELETE_LIFTING_STAT_OPTIMISTIC;

export const GET_LIFT_FEED_BY_USERNAME = 'GET_LIFT_FEED_BY_USERNAME';
export type GET_LIFT_FEED_BY_USERNAME = typeof GET_LIFT_FEED_BY_USERNAME;

export const CREATE_PROGRAM_LOG_FROM_TEMPLATE = 'CREATE_PROGRAM_LOG_FROM_TEMPLATE';
export type CREATE_PROGRAM_LOG_FROM_TEMPLATE = typeof CREATE_PROGRAM_LOG_FROM_TEMPLATE;

export const CREATE_PROGRAM_LOG_SCRATCH = 'CREATE_PROGRAM_LOG_SCRATCH';
export type CREATE_PROGRAM_LOG_SCRATCH = typeof CREATE_PROGRAM_LOG_SCRATCH;

export const REGISTER_USER = 'REGISTER_USER';
export type REGISTER_USER = typeof REGISTER_USER;

export const LOGIN_USER = 'LOGIN_USER';
export type LOGIN_USER = typeof LOGIN_USER;

//Friends List

export const REQUEST_FRIEND = 'REQUEST_FRIEND';
export type REQUEST_FRIEND = typeof REQUEST_FRIEND;

export const RESPOND_TO_FRIENDS_REQUEST = 'RESPOND_TO_FRIENDS_REQUEST';
export type RESPOND_TO_FRIENDS_REQUEST = typeof RESPOND_TO_FRIENDS_REQUEST;

export const LOAD_FRIENDS_LIST = 'LOAD_FRIENDS_LIST';
export type LOAD_FRIENDS_LIST = typeof LOAD_FRIENDS_LIST;

export const GET_USER_FRIENDS_LIST = 'GET_USER_FRIENDS_LIST';
export type GET_USER_FRIENDS_LIST = typeof GET_USER_FRIENDS_LIST;

export const LOAD_USER_SETTINGS = 'LOAD_USER_SETTINGS';
export type LOAD_USER_SETTINGS = typeof LOAD_USER_SETTINGS;

export const LOAD_ACCOUNT_NOTIFICATIONS = 'LOAD_ACCOUNT_NOTIFICATIONS';
export type LOAD_ACCOUNT_NOTIFICATIONS = typeof LOAD_ACCOUNT_NOTIFICATIONS;

export const CREATE_FIRST_VISIT_STATS = 'CREATE_FIRST_VISIT_STATS';
export type CREATE_FIRST_VISIT_STATS = typeof CREATE_FIRST_VISIT_STATS;

export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';
export type DEAUTHENTICATE_USER = typeof DEAUTHENTICATE_USER;

export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export type LOAD_USER_PROFILE = typeof LOAD_USER_PROFILE;

export const DESTROY_SESSION = 'DESTROY_SESSION';
export type DESTROY_SESSION = typeof DESTROY_SESSION;
